In [5]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
import time

In [6]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784')

C:\Users\harsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\_openml.py:932: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [7]:
X = mnist.data
Y = mnist.target
print('number of examples :', X.shape[0])

number of examples : 70000


In [8]:
x_time = time.time()
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state = 40, test_size = 0.14)
clf = RandomForestClassifier()
# clf.fit(X_train, Y_train)
y_time = time.time()
print(y_time-x_time)

0.5895981788635254


In [9]:
x_time = time.time()
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [ 35, 45],
    'n_estimators': [ 150, 200]
}

gs = GridSearchCV( clf, param_grid, cv=5, n_jobs=2 )
gs.fit(X_train, Y_train)

y_time = time.time()
print("Time required(in min)", (y_time-x_time)/60 )

print(gs.best_params_)
print(gs.best_score_)

Time required(in min) 57.09505125284195
{'criterion': 'gini', 'max_depth': 45, 'n_estimators': 200}
0.968903123265776


In [10]:
clf_best = RandomForestClassifier(**gs.best_params_)
clf_best.fit(X_train, Y_train)

RandomForestClassifier(max_depth=45, n_estimators=200)

In [11]:
Y_pred = clf_best.predict( X_test )
print('Accuracy Score on train data: ', accuracy_score(y_true=Y_train, y_pred=clf_best.predict(X_train)))
print('Accuracy Score on test data: ', accuracy_score(y_true=Y_test, y_pred=Y_pred))

Accuracy Score on train data:  1.0
Accuracy Score on test data:  0.9702071217222732


In [12]:
print("For the Test Cases : ")
f1score = f1_score(Y_test, Y_pred, average='macro')
print("F1 Score: ", f1score)
cm = confusion_matrix(Y_test, Y_pred)
print("Confusion Matrix:")
print(cm)

For the Test Cases : 
F1 Score:  0.9699329937774065
Confusion Matrix:
[[ 962    1    3    0    1    1    4    0    4    0]
 [   0 1070    1    1    1    0    2    1    1    1]
 [   3    0  976    4    5    0    3    8    6    0]
 [   2    0   14  992    0   11    1    8    7    4]
 [   2    2    2    0  946    0    4    1    3    6]
 [   1    2    0   10    2  819   11    1    2    4]
 [   4    6    0    0    0    3  921    0    1    0]
 [   1    1    6    2    7    0    0  997    1   12]
 [   3    1    6    8    6    9    0    1  921   14]
 [   5    3    2    8   15    4    1    7    4  905]]
