In [1]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
import time

from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784')

C:\Users\harsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\_openml.py:932: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [2]:
X = mnist.data
Y = mnist.target
print('number of examples :', X.shape[0])

number of examples : 70000


In [3]:
x_time = time.time()
# Since the Sample Size is too big and SVMs take a long time to be trained, hence we are using only a small size of the sample. 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state = 40, train_size = 0.3, test_size = 0.01)
clf = svm.SVC()
# clf.fit(X_train, Y_train)
y_time = time.time()
print("Time in (sec)", y_time-x_time)

Time in (sec) 0.1770164966583252


In [4]:
param_grid = {
    'kernel' : [ 'linear', 'poly', 'rbf', 'sigmoid' ]
}

x_time = time.time()
gs = GridSearchCV( clf, param_grid=param_grid, cv=2, n_jobs=3 )
gs.fit(X_train, Y_train)
y_time = time.time()
print("Time in (min)", (y_time-x_time)/60)

print('Best Hyperparameters : ', gs.best_params_)
print('Best score : ', gs.best_score_)

Time in (min) 2.8219338496526083
Best Hyperparameters :  {'kernel': 'rbf'}
Best score :  0.9614761904761905


In [5]:
clf_best = svm.SVC(**gs.best_params_)
clf_best.fit(X_train, Y_train) 

SVC()

In [6]:
x_time = time.time()
Y_pred_train = clf_best.predict( X_train )
Y_pred_test = clf_best.predict( X_test )
y_time = time.time()
print("Time in (sec)", y_time-x_time)
print('Accuracy Score on train data: ', accuracy_score(y_true=Y_train, y_pred=Y_pred_train))
print('Accuracy Score on test data: ', accuracy_score(y_true=Y_test, y_pred=Y_pred_test))

Time in (sec) 272.40338945388794
Accuracy Score on train data:  0.9871428571428571
Accuracy Score on test data:  0.9728571428571429


In [8]:
print("For the Test Cases : ")
f1score = f1_score(Y_test, Y_pred_test, average='macro')
print("F1 Score: ", f1score)
cm = confusion_matrix(Y_test, Y_pred_test)
print("Confusion Matrix:")
print(cm)

For the Test Cases : 
F1 Score:  0.9727005260105779
Confusion Matrix:
[[76  0  1  0  0  0  0  0  0  0]
 [ 0 74  1  0  0  0  0  0  0  1]
 [ 0  1 70  0  0  0  0  0  0  0]
 [ 0  0  1 75  0  0  0  1  1  0]
 [ 0  0  0  0 73  0  0  0  0  1]
 [ 0  0  0  0  0 59  2  0  0  0]
 [ 1  0  0  0  0  0 69  0  0  0]
 [ 0  0  0  0  0  0  0 64  0  2]
 [ 0  1  0  0  0  0  0  0 56  1]
 [ 0  0  0  1  2  1  0  0  0 65]]
