In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
import time

from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784')

C:\Users\harsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\_openml.py:932: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [2]:
X = mnist.data
Y = mnist.target
print('number of examples :', X.shape[0])

number of examples : 70000


In [3]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state = 40, test_size = 0.14)
clf = KNeighborsClassifier()
# clf.fit(X_train, Y_train)

In [4]:
# print(clf.n_neighbors)

x_time = time.time()
param_grid = {
    'n_neighbors': range(3, 7),
    'metric': ['euclidean', 'manhattan', 'minkowski']
}
random_search = RandomizedSearchCV(clf, param_distributions=param_grid, n_iter=5, cv=5, random_state=42, n_jobs=3 )
random_search.fit(X_train, Y_train)

y_time = time.time()
print(y_time-x_time)

print('Best hyperparameters:', random_search.best_params_)
print('Best score:', random_search.best_score_)

989.0390822887421
Best hyperparameters: {'n_neighbors': 3, 'metric': 'euclidean'}
Best score: 0.9709131631720718


In [5]:
clf_best = KNeighborsClassifier(**random_search.best_params_)
clf_best.fit(X_train, Y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

In [6]:
x_time = time.time()
Y_pred_test = clf_best.predict( X_test )
Y_pred_train = clf_best.predict( X_train )
y_time = time.time()
print("Time taken (in sec)", y_time-x_time)
print('Accuracy Score on train data: ', accuracy_score(y_true=Y_train, y_pred=Y_pred_train))
print('Accuracy Score on test data: ', accuracy_score(y_true=Y_test, y_pred=Y_pred_test))

Time taken (in sec) 60.60973119735718
Accuracy Score on train data:  0.9863785112709513
Accuracy Score on test data:  0.9705132129374554


In [9]:
print("For the Test Cases : ")
f1score = f1_score(Y_test, Y_pred_test, average='macro')
print("F1 Score: ", f1score)
cm = confusion_matrix(Y_test, Y_pred_test)
print("Confusion Matrix:")
print(cm)

For the Test Cases : 
F1 Score:  0.9701658400790091
Confusion Matrix:
[[ 968    1    2    0    0    1    3    0    1    0]
 [   0 1074    0    0    1    1    0    1    0    1]
 [   2    5  977    3    1    0    2    9    3    3]
 [   2    2    5 1008    0   15    1    1    3    2]
 [   1    9    1    0  939    0    2    1    0   13]
 [   3    2    1   15    2  815    9    1    1    3]
 [   2    4    0    0    1    2  926    0    0    0]
 [   1    7    3    0    2    0    0 1006    0    8]
 [   4   12    7   14   13   12    2    2  889   14]
 [   6    4    1    5   11    3    0   11    3  910]]
