In [1]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
import time

In [2]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784')

C:\Users\harsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\_openml.py:932: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [3]:
X = mnist.data
Y = mnist.target
print('number of examples :', X.shape[0])

number of examples : 70000


In [4]:
# x_time = time.time()
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state = 40, test_size = 0.14)
clf = MLPClassifier()
# y_time = time.time()
# print(y_time-x_time)

In [5]:
x_time = time.time()
param_grid = {
    'hidden_layer_sizes': [(10,), (50,), (100,), (10, 10), (50, 50), (100, 100)],
    'activation': ['logistic']
}

gs = GridSearchCV( clf, param_grid=param_grid, cv=5, n_jobs=-1 )
gs.fit(X_train, Y_train)

y_time = time.time()
print("Time in (min)", (y_time-x_time)/60)

print('Best Hyperparameters : ', gs.best_params_)
print('Best score : ', gs.best_score_)

Time in (min) 30.94943500359853
Best Hyperparameters :  {'activation': 'logistic', 'hidden_layer_sizes': (100, 100)}
Best score :  0.9588863284579823


In [ ]:
clf_best = MLPClassifier(**gs.best_params_)
clf_best.fit(X_train, Y_train) 

In [7]:
Y_pred_train = clf_best.predict( X_train )
Y_pred_test = clf_best.predict( X_test )
print('Accuracy Score on train data: ', accuracy_score(y_true=Y_train, y_pred=Y_pred_train))
print('Accuracy Score on test data: ', accuracy_score(y_true=Y_test, y_pred=Y_pred_test))

Accuracy Score on train data:  0.976793634445755
Accuracy Score on test data:  0.9655137230894807


In [10]:
print("For the Test Cases : ")
f1score = f1_score(Y_test, Y_pred_test, average='macro')
print("F1 Score: ", f1score)
cm = confusion_matrix(Y_test, Y_pred_test)
print("Confusion Matrix:")
print(cm)

For the Test Cases : 
F1 Score:  0.9650831865463741
Confusion Matrix:
[[ 967    1    2    0    0    2    3    0    0    1]
 [   0 1069    2    2    1    1    0    1    2    0]
 [   7    1  973    6    2    1    3    5    5    2]
 [   1    2    9  986    0   19    0    5   12    5]
 [   2    3    3    1  938    1    4    4    1    9]
 [   4    3    1   15    2  809    7    1    3    7]
 [   7    3    1    0    2    4  914    0    4    0]
 [   2    1    7    0    7    1    0  996    1   12]
 [   8    4    5    9    5   11    1    2  914   10]
 [   3    3    1    8   12    5    0   18    7  897]]
