In [1]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
import time

In [2]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784')

C:\Users\harsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\_openml.py:932: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [3]:
X = mnist.data
Y = mnist.target
print('number of examples :', X.shape[0])

number of examples : 70000


In [4]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state = 40, test_size = 0.14)
clf = DecisionTreeClassifier()
# clf.fit(X_train, Y_train)

In [75]:
# tree = clf.tree_
# print(tree.node_count)
# print(tree.max_depth)

In [5]:
x_time = time.time()
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [ 40, 50, None],
    'min_samples_split': [20, 50, 70, None],
    'max_features': ['sqrt', 'log2', None]
}

gs = GridSearchCV( clf, param_grid, cv=5, n_jobs=-1 )
gs.fit(X_train, Y_train)

y_time = time.time()
print("Time for Grid Parameters + ",  y_time-x_time)

print(gs.best_params_)
print(gs.best_score_)

C:\Users\harsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
90 fits failed out of a total of 360.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
90 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\harsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\harsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py", line 889, in fit
    super().fit(
  File "C:\Users\harsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\tree\_classes.py",

Time for Grid Parameters +  418.78473258018494
{'criterion': 'entropy', 'max_depth': None, 'max_features': None, 'min_samples_split': 20}
0.8718583650754097


In [6]:
clf_best = DecisionTreeClassifier(**gs.best_params_)
clf_best.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', min_samples_split=20)

In [7]:
Y_pred = clf_best.predict( X_test )
print('Accuracy Score on train data: ', accuracy_score(y_true=Y_train, y_pred=clf_best.predict(X_train)))
print('Accuracy Score on test data: ', accuracy_score(y_true=Y_test, y_pred=Y_pred))

Accuracy Score on train data:  0.9485207395471685
Accuracy Score on test data:  0.8757269666360575


In [11]:
print("For the Test Cases : ")
f1score = f1_score(Y_test, Y_pred, average='macro')
print("F1 Score: ", f1score)
cm = confusion_matrix(Y_test, Y_pred)
print("Confusion Matrix:")
print(cm)

For the Test Cases : 
F1 Score:  0.8741273264523134
Confusion Matrix:
[[ 913    1   13    5    2   16    9    4   10    3]
 [   0 1029    9   10    1    4    3    6   12    4]
 [  10    9  874   11   10   10   17   23   23   18]
 [   4    9   27  876    5   43    6   21   32   16]
 [   4    4    9    6  852    6   17   10   12   46]
 [  14    5    5   45   13  703   22    4   28   13]
 [  11    6   16    5   22   12  841    2   16    4]
 [   4    9   24    9   10    1    3  934    8   25]
 [  10   13   26   33   20   30   12   14  782   29]
 [  10    3    4   24   38   28    4   31   33  779]]
